///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package bubbles1000

import (
	"fmt"

	"github.com/xinliangnote/go-gin-api/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *Bubbles1000 {
	return new(Bubbles1000)
}

func NewQueryBuilder() *bubbles1000QueryBuilder {
	return new(bubbles1000QueryBuilder)
}

func (t *Bubbles1000) Create(db *gorm.DB) (id int32, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type bubbles1000QueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *bubbles1000QueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *bubbles1000QueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&Bubbles1000{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *bubbles1000QueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&Bubbles1000{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *bubbles1000QueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&Bubbles1000{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *bubbles1000QueryBuilder) First(db *gorm.DB) (*Bubbles1000, error) {
	ret := &Bubbles1000{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *bubbles1000QueryBuilder) QueryOne(db *gorm.DB) (*Bubbles1000, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *bubbles1000QueryBuilder) QueryAll(db *gorm.DB) ([]*Bubbles1000, error) {
	var ret []*Bubbles1000
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *bubbles1000QueryBuilder) Limit(limit int) *bubbles1000QueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *bubbles1000QueryBuilder) Offset(offset int) *bubbles1000QueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereId(p mysql.Predicate, value int32) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereIdIn(value []int32) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereIdNotIn(value []int32) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) OrderById(asc bool) *bubbles1000QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereName(p mysql.Predicate, value string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "name", p),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereNameIn(value []string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "name", "IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereNameNotIn(value []string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "name", "NOT IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) OrderByName(asc bool) *bubbles1000QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "name "+order)
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereSlug(p mysql.Predicate, value string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "slug", p),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereSlugIn(value []string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "slug", "IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereSlugNotIn(value []string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "slug", "NOT IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) OrderBySlug(asc bool) *bubbles1000QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "slug "+order)
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereSymbol(p mysql.Predicate, value string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "symbol", p),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereSymbolIn(value []string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "symbol", "IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereSymbolNotIn(value []string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "symbol", "NOT IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) OrderBySymbol(asc bool) *bubbles1000QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "symbol "+order)
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereDominance(p mysql.Predicate, value float64) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "dominance", p),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereDominanceIn(value []float64) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "dominance", "IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereDominanceNotIn(value []float64) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "dominance", "NOT IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) OrderByDominance(asc bool) *bubbles1000QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "dominance "+order)
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereImage(p mysql.Predicate, value string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "image", p),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereImageIn(value []string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "image", "IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereImageNotIn(value []string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "image", "NOT IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) OrderByImage(asc bool) *bubbles1000QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "image "+order)
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereRank(p mysql.Predicate, value int32) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "rank", p),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereRankIn(value []int32) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "rank", "IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereRankNotIn(value []int32) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "rank", "NOT IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) OrderByRank(asc bool) *bubbles1000QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "rank "+order)
	return qb
}

func (qb *bubbles1000QueryBuilder) WherePrice(p mysql.Predicate, value float64) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "price", p),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WherePriceIn(value []float64) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "price", "IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WherePriceNotIn(value []float64) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "price", "NOT IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) OrderByPrice(asc bool) *bubbles1000QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "price "+order)
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereMarketcap(p mysql.Predicate, value int64) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "marketcap", p),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereMarketcapIn(value []int64) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "marketcap", "IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereMarketcapNotIn(value []int64) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "marketcap", "NOT IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) OrderByMarketcap(asc bool) *bubbles1000QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "marketcap "+order)
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereVolume(p mysql.Predicate, value int64) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "volume", p),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereVolumeIn(value []int64) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "volume", "IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereVolumeNotIn(value []int64) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "volume", "NOT IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) OrderByVolume(asc bool) *bubbles1000QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "volume "+order)
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereCgId(p mysql.Predicate, value string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "cg_id", p),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereCgIdIn(value []string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "cg_id", "IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereCgIdNotIn(value []string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "cg_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) OrderByCgId(asc bool) *bubbles1000QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "cg_id "+order)
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereSymbols(p mysql.Predicate, value string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "symbols", p),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereSymbolsIn(value []string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "symbols", "IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereSymbolsNotIn(value []string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "symbols", "NOT IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) OrderBySymbols(asc bool) *bubbles1000QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "symbols "+order)
	return qb
}

func (qb *bubbles1000QueryBuilder) WherePerformance(p mysql.Predicate, value string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "performance", p),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WherePerformanceIn(value []string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "performance", "IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WherePerformanceNotIn(value []string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "performance", "NOT IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) OrderByPerformance(asc bool) *bubbles1000QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "performance "+order)
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereRankDiffs(p mysql.Predicate, value string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "rank_diffs", p),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereRankDiffsIn(value []string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "rank_diffs", "IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereRankDiffsNotIn(value []string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "rank_diffs", "NOT IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) OrderByRankDiffs(asc bool) *bubbles1000QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "rank_diffs "+order)
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereExchangePrices(p mysql.Predicate, value string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "exchange_prices", p),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereExchangePricesIn(value []string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "exchange_prices", "IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) WhereExchangePricesNotIn(value []string) *bubbles1000QueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "exchange_prices", "NOT IN"),
		value,
	})
	return qb
}

func (qb *bubbles1000QueryBuilder) OrderByExchangePrices(asc bool) *bubbles1000QueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "exchange_prices "+order)
	return qb
}
