///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package news

import (
	"fmt"
	"time"

	"github.com/xinliangnote/go-gin-api/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *News {
	return new(News)
}

func NewQueryBuilder() *newsQueryBuilder {
	return new(newsQueryBuilder)
}

func (t *News) Create(db *gorm.DB) (id int32, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type newsQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *newsQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *newsQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&News{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *newsQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&News{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *newsQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&News{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *newsQueryBuilder) First(db *gorm.DB) (*News, error) {
	ret := &News{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *newsQueryBuilder) QueryOne(db *gorm.DB) (*News, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *newsQueryBuilder) QueryAll(db *gorm.DB) ([]*News, error) {
	var ret []*News
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *newsQueryBuilder) Limit(limit int) *newsQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *newsQueryBuilder) Offset(offset int) *newsQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *newsQueryBuilder) WhereId(p mysql.Predicate, value int32) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) WhereIdIn(value []int32) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) WhereIdNotIn(value []int32) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) OrderById(asc bool) *newsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *newsQueryBuilder) WhereTitle(p mysql.Predicate, value string) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "title", p),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) WhereTitleIn(value []string) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "title", "IN"),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) WhereTitleNotIn(value []string) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "title", "NOT IN"),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) OrderByTitle(asc bool) *newsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "title "+order)
	return qb
}

func (qb *newsQueryBuilder) WhereSubTitle(p mysql.Predicate, value string) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sub_title", p),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) WhereSubTitleIn(value []string) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sub_title", "IN"),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) WhereSubTitleNotIn(value []string) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sub_title", "NOT IN"),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) OrderBySubTitle(asc bool) *newsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "sub_title "+order)
	return qb
}

func (qb *newsQueryBuilder) WhereWebLink(p mysql.Predicate, value string) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "web_link", p),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) WhereWebLinkIn(value []string) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "web_link", "IN"),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) WhereWebLinkNotIn(value []string) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "web_link", "NOT IN"),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) OrderByWebLink(asc bool) *newsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "web_link "+order)
	return qb
}

func (qb *newsQueryBuilder) WhereBinanceId(p mysql.Predicate, value string) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "binance_id", p),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) WhereBinanceIdIn(value []string) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "binance_id", "IN"),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) WhereBinanceIdNotIn(value []string) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "binance_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) OrderByBinanceId(asc bool) *newsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "binance_id "+order)
	return qb
}

func (qb *newsQueryBuilder) WherePublishTime(p mysql.Predicate, value time.Time) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "publish_time", p),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) WherePublishTimeIn(value []time.Time) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "publish_time", "IN"),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) WherePublishTimeNotIn(value []time.Time) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "publish_time", "NOT IN"),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) OrderByPublishTime(asc bool) *newsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "publish_time "+order)
	return qb
}

func (qb *newsQueryBuilder) WhereCreatedAt(p mysql.Predicate, value time.Time) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", p),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) WhereCreatedAtIn(value []time.Time) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "IN"),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) WhereCreatedAtNotIn(value []time.Time) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) OrderByCreatedAt(asc bool) *newsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "created_at "+order)
	return qb
}

func (qb *newsQueryBuilder) WhereType(p mysql.Predicate, value int32) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "type", p),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) WhereTypeIn(value []int32) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "type", "IN"),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) WhereTypeNotIn(value []int32) *newsQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "type", "NOT IN"),
		value,
	})
	return qb
}

func (qb *newsQueryBuilder) OrderByType(asc bool) *newsQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "type "+order)
	return qb
}
