///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package crypto_fear_greed

import (
	"fmt"

	"github.com/xinliangnote/go-gin-api/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *CryptoFearGreed {
	return new(CryptoFearGreed)
}

func NewQueryBuilder() *cryptoFearGreedQueryBuilder {
	return new(cryptoFearGreedQueryBuilder)
}

func (t *CryptoFearGreed) Create(db *gorm.DB) (id int32, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type cryptoFearGreedQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *cryptoFearGreedQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *cryptoFearGreedQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&CryptoFearGreed{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *cryptoFearGreedQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&CryptoFearGreed{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *cryptoFearGreedQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&CryptoFearGreed{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *cryptoFearGreedQueryBuilder) First(db *gorm.DB) (*CryptoFearGreed, error) {
	ret := &CryptoFearGreed{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *cryptoFearGreedQueryBuilder) QueryOne(db *gorm.DB) (*CryptoFearGreed, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *cryptoFearGreedQueryBuilder) QueryAll(db *gorm.DB) ([]*CryptoFearGreed, error) {
	var ret []*CryptoFearGreed
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *cryptoFearGreedQueryBuilder) Limit(limit int) *cryptoFearGreedQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) Offset(offset int) *cryptoFearGreedQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) WhereId(p mysql.Predicate, value int32) *cryptoFearGreedQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) WhereIdIn(value []int32) *cryptoFearGreedQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) WhereIdNotIn(value []int32) *cryptoFearGreedQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) OrderById(asc bool) *cryptoFearGreedQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) WhereDate(p mysql.Predicate, value string) *cryptoFearGreedQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "date", p),
		value,
	})
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) WhereDateIn(value []string) *cryptoFearGreedQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "date", "IN"),
		value,
	})
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) WhereDateNotIn(value []string) *cryptoFearGreedQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "date", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) OrderByDate(asc bool) *cryptoFearGreedQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "date "+order)
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) WhereCurrentValue(p mysql.Predicate, value int32) *cryptoFearGreedQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "current_value", p),
		value,
	})
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) WhereCurrentValueIn(value []int32) *cryptoFearGreedQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "current_value", "IN"),
		value,
	})
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) WhereCurrentValueNotIn(value []int32) *cryptoFearGreedQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "current_value", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) OrderByCurrentValue(asc bool) *cryptoFearGreedQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "current_value "+order)
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) WhereBearishValue(p mysql.Predicate, value int32) *cryptoFearGreedQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "bearish_value", p),
		value,
	})
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) WhereBearishValueIn(value []int32) *cryptoFearGreedQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "bearish_value", "IN"),
		value,
	})
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) WhereBearishValueNotIn(value []int32) *cryptoFearGreedQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "bearish_value", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) OrderByBearishValue(asc bool) *cryptoFearGreedQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "bearish_value "+order)
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) WhereBullishValue(p mysql.Predicate, value int32) *cryptoFearGreedQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "bullish_value", p),
		value,
	})
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) WhereBullishValueIn(value []int32) *cryptoFearGreedQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "bullish_value", "IN"),
		value,
	})
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) WhereBullishValueNotIn(value []int32) *cryptoFearGreedQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "bullish_value", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) OrderByBullishValue(asc bool) *cryptoFearGreedQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "bullish_value "+order)
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) WhereLastWeekValue(p mysql.Predicate, value int32) *cryptoFearGreedQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "last_week_value", p),
		value,
	})
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) WhereLastWeekValueIn(value []int32) *cryptoFearGreedQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "last_week_value", "IN"),
		value,
	})
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) WhereLastWeekValueNotIn(value []int32) *cryptoFearGreedQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "last_week_value", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cryptoFearGreedQueryBuilder) OrderByLastWeekValue(asc bool) *cryptoFearGreedQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "last_week_value "+order)
	return qb
}
